/*PROBLEM STATEMENT 02:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include<stdio.h>

int main()
{
    long i = 2;
    long prev = 1;
    long sum = 0;
    
    while(i<=4000000)
    {
        long temp = i;
        if(i%2==0) sum+=i;
        i += prev;
        prev = temp;
    }

    printf("Sum of even-valued terms: %ld", sum);

}